---
common-steps:
  - &removevirtualenv
    run:
      name: Removes the upstream virtualenv from the original container image
      command: sudo pip uninstall virtualenv -y

  - &install_packaging_dependencies
    run:
      name: Install Debian packaging dependencies and download wheels
      command: |
        mkdir ~/packaging && cd ~/packaging
        git config --global --unset url.ssh://git@github.com.insteadof
        git clone https://github.com/freedomofpress/securedrop-debian-packaging.git
        cd securedrop-debian-packaging
        make install-deps
        PKG_DIR=~/project make requirements

  - &verify_requirements
    run:
      name: Ensure that build-requirements.txt and requirements.txt are in sync.
      command: |
        cd ~/project
        # Return 1 if unstaged changes exist (after `make requirements` in the
        # previous run step), else return 0.
        git diff --quiet

  - &build_debian_package
    run:
      name: Build debian package
      command: |
        cd ~/project
        ./update_version.sh 1000.0  # Dummy version number, doesn't matter what we put here
        cd ~/packaging/securedrop-debian-packaging
        export PKG_VERSION=1000.0
        export PKG_PATH=/home/circleci/project/
        find $PKG_PATH
        make securedrop-log

version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3.7-buster
    steps:
      - checkout
      - run:
          name: Run tests
          command: python3 -m unittest

  build-buster:
    docker:
      - image: circleci/python:3.7-buster
    steps:
      - checkout
      - *removevirtualenv
      - *install_packaging_dependencies
      - *verify_requirements
      - *build_debian_package

workflows:
  version: 2
  per_pr:
    jobs:
      - test
      - build-buster
